# Generated by Django 4.2.7 on 2023-11-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='batchone.instructor')),
            ],
        ),
    ]
